#include <iostream>
#include <string>
#include <cstring>
#include <algorithm>
#include <ctime>
#include <cstdlib>
#include <vector>
#include <fstream>
#include <chrono>
#include <thread>
#include <iomanip>
#include <stdio.h>
#include <string>
#include <string.h>
#include <cstdint>
#include <sstream>
#include "SHA256.h"